# Generated by Django 5.2.7 on 2025-10-24 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Who owns this book (e.g., the employee who lent it to the company).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookloan',
            index=models.Index(fields=['book'], name='books_bookl_book_id_7c3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='bookloan',
            index=models.Index(fields=['returned_at'], name='books_bookl_returne_911c4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookloan',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('book',), name='unique_active_loan_per_book'),
        ),
    ]
