# Generated by Django 5.2.7 on 2025-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_owner_bookloan_books_bookl_book_id_7c3e3a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.CharField(blank=True, help_text='Name of the person or department who owns this book', max_length=200, null=True),
        ),
    ]
