# Generated by Django 5.2.7 on 2025-10-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='book',
            name='qr_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
